<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Signup Template · Bootstrap v5.1</title>

  <!-- Bootstrap core CSS -->
  <link href="<?php echo URLROOT?>node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <!-- Custom styles for this template -->
  <link href="<?php echo URLROOT?>public/assets/css/signin.css" rel="stylesheet">
</head>
<body class="text-center container">
<div class="container">
  <main class="form-signin">
  <h1 class="h3 mb-3 fw-normal">Sign In</h1>
  <?php echo $this->tag->form(
    [
        "login",
        "method" => "post",
    ]
);?>
     <div class="form-floating">
        <?php echo $this->tag->emailField(["email","id"=>"floatingInput","class"=>"form-control","required"=>"true"]); ?>
        <label for="floatingInput">Email address </label>
      </div>
      <div class="form-floating">
        <?php echo $this->tag->passwordField(["password","id"=>"floatingpassword","class"=>"form-control","required"=>"true"]); ?>
        <label for="floatingPassword">Password  </label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember" name="radio"> Remember me
        </label>
      </div>
      <button class="w-100 btn btn-lg btn-primary" name="submit" type="submit">Sign in</button>
      <div class="message text-danger">
       <p> <?php if (!empty($data)) {
            echo $data;
} ?></p>
      </div>
      <p class="mt-5 mb-3 text-muted">&copy; CEDCOSS Technologies</p>
    </form>

  </main>
</div>
</body>

</html>