<?php
include APP_PATH."/views/header.phtml";
?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center 
        pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">All Users</h1>
        </div>

        <h2>Section title</h2>
        <div class="table-responsive">
            <?php
            
            $html = "";
            $html .= '<table id="myTable" class="table table-striped table-sm">     
        <tr>
          <th scope="col">User Id</th>
          <th scope="col">Name</th>
          <th scope="col">email</th>
          <th scope="col">Role</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
      
      ';
            foreach ($data as $k => $v) {
                $html .= '<tr>
        <td>' . $v->id . '</td>
        <td>' . $v->name . '</td>
        <td>' . $v->email . '</td>
        <td>' . $v->role . '</td>
        <td><a href = "'.URLROOT.'admin/updateUser?id='.$v->id.'" class="btn btn-primary">Edit</a></td>
        <td><form action="" method="POST">
        <input type="hidden" name="id" value="' . $v->id . '">
        <button type="submit" name="delete" class="userEdit btn btn-danger">Delete</button>
        </form></td>
        </tr>';
            }
            $html .= '</table>';
            echo $html;

            ?>
          </div>
                <br>
                <br>
            <a href="<?php echo URLROOT;?>admin/addNewUser" class="btn btn-info">Add New User</a>
        </div>
      </main>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" 
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
  crossorigin="anonymous"></script>
  <script>
    $(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    // console.log(value);
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
$(function () {
    $("body").on("click","#submit1",function () {
        alert("Are you sure?");
    });
});
  </script>
</body>

</html>